#pragma once

// The embedded font blobs are generated by binary_to_compressed_c into
// font_*.cpp, which CGuiFontManager.cpp #includes TEXTUALLY (those files are in
// no build-system list). Their definitions are `const` at namespace scope,
// which in C++ means INTERNAL linkage -- binary_to_compressed_c's -nostatic
// removes the `static` keyword but not the linkage, so nothing outside that one
// translation unit can reference them. Verified with nm:
// __ZL34font_inter_regular_compressed_data (the _ZL prefix IS internal
// linkage), and the _compressed_size symbols are constant-folded away entirely.
//
// A prior `extern` declaration fixes it: [basic.link]/4 exempts a name
// "previously declared to have external linkage". So this header must be
// included by CGuiFontManager.cpp BEFORE the textual includes, and by any host
// that wants the same bytes -- which is the point, since the alternative is
// shipping a second ~830 KB copy of the same fonts as assets.
//
// Regenerating with generate_fonts.sh does not disturb this: the generated
// files define, this header declares, and the linkage is decided here.
//
// INCLUDE IT AS "Fonts/MTEmbeddedFonts.h". The include paths expose
// src/Embedded, not src/Embedded/Fonts. The bare form compiles on macOS anyway
// (the Xcode projects use a recursive src/** header search) and fails on Linux
// and Windows -- which is exactly how a change ships green on one platform.
//
// The array bounds are deliberately omitted. The definitions size themselves
// from the blob (e.g. [268044/4]), and repeating those numbers here would be a
// second copy to keep in step with every regeneration; an unbounded extern
// array declaration is completed by its definition and indexes identically.
// The ELEMENT TYPE, however, must match byte for byte: a mismatch there is an
// ODR violation, not a compile error -- it links and then misreads the data.

extern const unsigned int font_inter_regular_compressed_size;
extern const unsigned int font_inter_regular_compressed_data[];
extern const unsigned int font_inter_bold_compressed_size;
extern const unsigned int font_inter_bold_compressed_data[];
extern const unsigned int font_inter_italic_compressed_size;
extern const unsigned int font_inter_italic_compressed_data[];
extern const unsigned int font_inter_bold_italic_compressed_size;
extern const unsigned int font_inter_bold_italic_compressed_data[];
extern const unsigned int font_jetbrains_mono_compressed_size;
extern const unsigned int font_jetbrains_mono_compressed_data[];
