"""Fragment emission: the four build-system files, the generated header, the
stamp and the override overlay.

Everything here lands under $MT_OUT, outside all five checkouts. Nothing this
module writes is tracked by any repository.
"""

import json
import os

from resolve import (app_visible_defines, enabled_flags, engine_only_defines,
                     ffmpeg_mode)
from vocab import COMMERCIAL_KEY, PRIVATE_KEY, SYMBOLS_KEY, load_app_licences, APP_LICENCES_FILE

BANNER = "generated by mtcaps; do not edit, do not commit"


def _write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    # Bytes, not text mode: newline stays "\n" on every platform, so two
    # `resolve` runs produce byte-identical fragments (#4.4.5 idempotence).
    data = text.encode("utf-8")
    # Skip the write when the file already holds these bytes. resolve runs on
    # EVERY build and every artefact here feeds a build system that keys on
    # mtime -- an identical-content rewrite recompiled every TU including the
    # generated header (observed on Linux, HANDOVER item 6).
    try:
        with open(path, "rb") as f:
            if f.read() == data:
                return
    except OSError:
        pass
    with open(path, "wb") as f:
        f.write(data)


def store_settings(meta):
    """MT_STORE_<UNIT> for every build unit on this platform (L16).

    Delivered as string settings in the same shape as MT_FFMPEG_BUILD_MODE and
    the decoder policy, so the four readers that already carry string values to
    the producing scripts need one wider pattern rather than a new mechanism
    each. A producer reads its own -- build-sdl3.sh reads MT_STORE_SDL3 -- and
    computes nothing: keys are mtcaps' business, and a shell that computed one
    would be the second implementation of a key that this system has already
    had to delete once.
    """
    return dict(("MT_STORE_%s" % name.upper(), path)
                for name, path in sorted(meta.get("stores", {}).items()))


def emit_all(vocab, values, canonical, out, include_dir, meta):
    """Writes every artefact and returns the list of paths written."""
    written = []
    written.append(emit_cmake(vocab, values, canonical, out, include_dir, meta))
    written.append(emit_xcconfig(vocab, values, canonical, out, include_dir, meta))
    written.append(emit_props(vocab, values, canonical, out, include_dir, meta))
    written.append(emit_header(vocab, values, canonical, include_dir))
    written.append(emit_msbuild_ide_defines(vocab, values, out))
    written.append(emit_llama_version_placeholder(include_dir))
    written.append(emit_stamp(out, meta, canonical))
    written.append(emit_licenses(vocab, values, canonical, out, meta))
    return written


# ---------------------------------------------------------------------------
# Linux -- CMake
# ---------------------------------------------------------------------------

def _camel(key):
    """MT_FFMPEG_DECODERS_WITHHELD -> MTFFmpegDecodersWithheld, matching the
    MTFFmpegBuildMode / MTReleaseSymbols properties beside it."""
    parts = key.split("_")
    out = "MT" + ("FFmpeg" if parts[1] == "FFMPEG" else parts[1].capitalize())
    for p in parts[2:]:
        out += p.capitalize()
    return out


def ffmpeg_policy(vocab, values):
    """The FFmpeg decoder policy for the resolved mode, as four space-separated
    lists: decoders, parsers, demuxers, and the withheld set.

    ONE SHAPE FOR ALL OF THEM, and it is the shape MT_FFMPEG_BUILD_MODE
    already uses -- a space-separated string, not a CMake `;`-list -- because
    the three readers that carry these values into the codec scripts parse
    fragments line by line with a sed and two regexes. A second shape would
    mean a second parser in each of them.

    The withheld set is emitted SEPARATELY from the decoder list rather than
    folded into it, because the scripts need both: the configure line wants
    the union for `full`, and the guard wants to know which names are the
    withheld ones. Deriving one from the other in three scripts is how the
    lists drifted apart in the first place.
    """
    ff = vocab.get("MT_CAP_VIDEO_PLAYBACK").get("ffmpeg", {})
    full = ffmpeg_mode(values) == "full"
    decoders = list(ff.get("decoders_base", []))
    parsers = list(ff.get("parsers_base", []))
    if full:
        decoders += ff.get("decoders_withheld", [])
        parsers += ff.get("parsers_withheld", [])
    return {
        "MT_FFMPEG_DECODERS": " ".join(decoders),
        "MT_FFMPEG_PARSERS": " ".join(parsers),
        "MT_FFMPEG_DEMUXERS": " ".join(ff.get("demuxers", [])),
        "MT_FFMPEG_DECODERS_WITHHELD": " ".join(ff.get("decoders_withheld", [])),
    }


def cmake_path(path):
    r"""A path CMake can read on every platform.

    CMake parses `\U` inside a quoted argument as a character escape and fails
    the whole fragment, so a Windows path spelled with backslashes is a syntax
    error rather than a wrong value. Forward slashes are accepted everywhere
    CMake accepts a path, on Windows included.
    """
    return path.replace("\\", "/")


def emit_cmake(vocab, values, canonical, out, include_dir, meta=None):
    lines = ["# %s" % BANNER, ""]
    lines.append('set(MT_CAPS_RESOLVED "%s")' % canonical)
    lines.append('set(MT_CAPS_INCLUDE_DIR "%s")' % cmake_path(include_dir))
    lines.append('set(MT_CAPS_BUILD_DIR "%s")' % cmake_path(os.path.dirname(include_dir)))
    lines.append("")
    lines.append("# Capabilities, as CMake variables AND as compile definitions.")
    for key in vocab.keys:
        lines.append("set(%s %d)" % (key, values[key]))
    lines.append("")
    lines.append("# Library flags. Every known flag appears, on or OFF: emitting only")
    lines.append("# the on ones leaves the rest UNDEFINED, and the #ifdef family")
    lines.append('# defaults off while the value style defaults on -- so "absent"')
    lines.append("# means two different things depending on the guard it meets.")
    flags = enabled_flags(vocab, values, platform=(meta or {}).get("platform"))
    for flag, value in flags.items():
        lines.append("set(%s %d)" % (flag, value))
    lines.append("")
    lines.append("# The KEYS, not a frozen list of KEY=VALUE pairs.")
    lines.append("#")
    lines.append("# mt_apply_capabilities re-reads each variable's CURRENT value at call")
    lines.append("# time. A baked list would freeze the values as of generation, and")
    lines.append("# CMakeLists.txt can still legitimately change one afterwards -- the")
    lines.append("# libheif downgrade does exactly that. With a frozen list the engine")
    lines.append("# would compile every TU with MT_ENABLE_LIBHEIF=1 while neither the")
    lines.append("# include dirs nor the library were added: a hard failure behind a")
    lines.append("# warning that claimed the feature had been disabled.")
    lines.append("set(MT_CAPS_CAPABILITY_KEYS")
    for key in vocab.keys:
        lines.append("    %s" % key)
    lines.append(")")
    lines.append("set(MT_CAPS_FLAG_KEYS")
    for flag in flags:
        lines.append("    %s" % flag)
    lines.append(")")
    lines.append("set(MT_CAPS_COMMERCIAL %d)" % values[COMMERCIAL_KEY])
    lines.append("set(MT_CAPS_PRIVATE %d)" % values[PRIVATE_KEY])
    lines.append("# Build-settings mode values (decision 0.5 / 0.2) -- values, not defines.")
    lines.append("set(MT_RELEASE_SYMBOLS %d)" % values[SYMBOLS_KEY])
    lines.append('set(MT_FFMPEG_BUILD_MODE "%s")' % ffmpeg_mode(values))
    for k, v in sorted(ffmpeg_policy(vocab, values).items()):
        lines.append('set(%s "%s")' % (k, v))
    # Through cmake_path, like MT_CAPS_INCLUDE_DIR above. The store paths are
    # the first ABSOLUTE paths this fragment carried that are not already
    # normalised, and on Windows they broke it outright (`C:\Users\...`).
    for k, v in sorted(store_settings(meta or {}).items()):
        lines.append('set(%s "%s")' % (k, cmake_path(v)))
    lines.append("")
    lines.append("function(mt_apply_capabilities target)")
    lines.append("    set(_mt_defs \"\")")
    lines.append("    foreach(_k IN LISTS MT_CAPS_CAPABILITY_KEYS MT_CAPS_FLAG_KEYS)")
    lines.append("        # ${_k} expands to the NAME, so if(${_k}) tests the variable.")
    lines.append("        if(${_k})")
    lines.append("            list(APPEND _mt_defs \"${_k}=1\")")
    lines.append("        else()")
    lines.append("            list(APPEND _mt_defs \"${_k}=0\")")
    lines.append("        endif()")
    lines.append("    endforeach()")
    lines.append("")
    lines.append("    # MT_COMMERCIAL_BUILD is ABSENT when the mode is off, never =0. Every")
    lines.append("    # guard on it in the tree is presence-style, and `#ifdef X` is TRUE")
    lines.append("    # when X is defined as 0 -- so emitting =0 would take all 30 sites")
    lines.append("    # down the COMMERCIAL branch, including the licence-audit tests")
    lines.append("    # written to catch exactly that.")
    lines.append("    if(MT_CAPS_COMMERCIAL)")
    lines.append("        list(APPEND _mt_defs MT_COMMERCIAL_BUILD=1)")
    lines.append("    endif()")
    lines.append("    # MT_PRIVATE_BUILD: same presence-style rule, same reason.")
    lines.append("    if(MT_CAPS_PRIVATE)")
    lines.append("        list(APPEND _mt_defs MT_PRIVATE_BUILD=1)")
    lines.append("    endif()")
    lines.append("")
    lines.append("    target_compile_definitions(${target} PUBLIC ${_mt_defs})")
    lines.append('    target_include_directories(${target} PUBLIC "${MT_CAPS_INCLUDE_DIR}")')
    lines.append("endfunction()")
    lines.append("")

    path = os.path.join(out, "MTEngineCapabilities.cmake")
    _write(path, "\n".join(lines))
    return path


# ---------------------------------------------------------------------------
# macOS -- xcconfig
#
# NOT imported by any Xcode project. A baseConfigurationReference is a tracked
# path and $MT_OUT ends in <caps-hash>, so no tracked reference can name this
# file. It is an artefact the WRAPPER reads and turns into xcodebuild settings.
# What carries a baseConfigurationReference is a *tracked* xcconfig holding the
# target's own defaults plus the consumption line
#   GCC_PREPROCESSOR_DEFINITIONS = $(inherited) $(MT_CAPS_DEFINES)
# Two files, two jobs, one name -- which is what three earlier drafts confused.
#
# So this file emits each value as a STANDALONE assignment the wrapper can read
# back, and folds nothing into GCC_PREPROCESSOR_DEFINITIONS.
# ---------------------------------------------------------------------------

def emit_xcconfig(vocab, values, canonical, out, include_dir, meta=None):
    lines = ["// %s" % BANNER,
             "//",
             "// This file is READ BY build-macos.sh and imported by nothing. See emit.py.",
             ""]
    for key in vocab.keys:
        lines.append("%s = %d" % (key, values[key]))
    lines.append("")
    for flag, value in enabled_flags(vocab, values, platform=(meta or {}).get("platform")).items():
        lines.append("%s = %d" % (flag, value))
    lines.append("")
    # Build-settings mode values -- VALUES only, never defines: decision 0.5
    # says nothing may guard code on the symbols key, and the ffmpeg mode is a
    # script input, not a compile-time branch.
    lines.append("MT_RELEASE_SYMBOLS = %d" % values[SYMBOLS_KEY])
    lines.append("MT_FFMPEG_BUILD_MODE = %s" % ffmpeg_mode(values))
    for k, v in sorted(ffmpeg_policy(vocab, values).items()):
        lines.append("%s = %s" % (k, v))
    for k, v in sorted(store_settings(meta or {}).items()):
        lines.append("%s = %s" % (k, v))
    lines.append("")
    lines.append("MT_CAPS_DEFINES = %s" % " ".join(
        app_visible_defines(vocab, values, platform=(meta or {}).get("platform"))))
    lines.append("MT_CAPS_DEFINES_ENGINE = %s" % " ".join(engine_only_defines(vocab, values)))
    lines.append("MT_CAPS_INCLUDE_DIR = %s" % include_dir)
    lines.append("MT_CAPS_BUILD_DIR = %s" % os.path.dirname(include_dir))
    lines.append("MT_CAPS_RESOLVED = %s" % canonical)
    lines.append("")

    path = os.path.join(out, "MTEngineCaps.xcconfig")
    _write(path, "\n".join(lines))
    return path


# ---------------------------------------------------------------------------
# Windows -- MSBuild
# ---------------------------------------------------------------------------

def emit_props(vocab, values, canonical, out, include_dir, meta=None):
    # platform="windows": this fragment is imported ONLY by MSBuild (see the
    # section header below), so it always reflects Windows reality, regardless
    # of which --platform a given `resolve` invocation happened to run under.
    # See PLATFORM_UNAVAILABLE_FLAGS in resolve.py for why.
    defines = []
    for key in vocab.keys:
        defines.append("%s=%d" % (key, values[key]))
    for flag, value in enabled_flags(vocab, values, platform=(meta or {}).get("platform", "windows")).items():
        defines.append("%s=%d" % (flag, value))
    if values[COMMERCIAL_KEY] == 1:
        defines.append("MT_COMMERCIAL_BUILD=1")
    # Presence-style, same as above: absent when off, never =0.
    if values[PRIVATE_KEY] == 1:
        defines.append("MT_PRIVATE_BUILD=1")

    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- %s -->" % BANNER,
        '<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">',
        "  <PropertyGroup>",
        "    <MTCapsResolved>%s</MTCapsResolved>" % canonical,
        "    <MTCapsIncludeDir>%s</MTCapsIncludeDir>" % include_dir,
        "    <MTCapsBuildDir>%s</MTCapsBuildDir>" % os.path.dirname(include_dir),
        "    <MTReleaseSymbols>%d</MTReleaseSymbols>" % values[SYMBOLS_KEY],
        "    <MTFFmpegBuildMode>%s</MTFFmpegBuildMode>" % ffmpeg_mode(values),
    ] + [
        # MSBuild property names cannot carry the MT_FFMPEG_ prefix's
        # underscores by convention here, so they follow the CamelCase of
        # their neighbours; the codec script reads them through the
        # environment the driver builds, not from this file.
        "    <%s>%s</%s>" % (_camel(k), v, _camel(k))
        for k, v in sorted(ffmpeg_policy(vocab, values).items())
    ] + [
        # Per-unit stores, so an IDE build reaches the same directories the
        # driver does. MTStoreSdl3, MTStoreVideoCodecs, ...
        "    <%s>%s</%s>" % (_camel(k), v, _camel(k))
        for k, v in sorted(store_settings(meta or {}).items())
    ] + [
        "  </PropertyGroup>",
        "  <PropertyGroup>",
    ]
    for key in vocab.keys:
        lines.append("    <%s>%d</%s>" % (key, values[key], key))
    for flag, value in enabled_flags(vocab, values, platform="windows").items():
        lines.append("    <%s>%d</%s>" % (flag, value, flag))
    lines += [
        "  </PropertyGroup>",
        "  <ItemDefinitionGroup>",
        "    <ClCompile>",
        "      <PreprocessorDefinitions>%s;%%(PreprocessorDefinitions)</PreprocessorDefinitions>"
        % ";".join(defines),
        "      <AdditionalIncludeDirectories>$(MTCapsIncludeDir);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>",
        "      <!-- Decision 0.5: debug info is ALWAYS generated (the app",
        "           projects carried no GenerateDebugInformation at all, so",
        "           Release links emitted no PDB); MT_RELEASE_SYMBOLS decides",
        "           only whether the PDB SHIPS, and the driver's deploy stage",
        "           enforces that half. -->",
        "      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>",
        "    </ClCompile>",
        "    <Link>",
        "      <GenerateDebugInformation>true</GenerateDebugInformation>",
        "    </Link>",
        "  </ItemDefinitionGroup>",
        "</Project>",
        "",
    ]
    path = os.path.join(out, "MTEngineCaps.props")
    _write(path, "\n".join(lines))
    return path


# ---------------------------------------------------------------------------
# All platforms -- the generated header
# ---------------------------------------------------------------------------

def emit_header(vocab, values, canonical, include_dir):
    caps = vocab.keys
    L = []
    A = L.append
    A("// %s" % BANNER)
    A("//")
    A("// ======================================================================")
    A("// WHAT THIS FILE IS FOR")
    A("// ======================================================================")
    A("//")
    A("// It lets APPLICATION SOURCE CODE ask about capabilities. That is a")
    A("// different job from the other four generated fragments, which tell a")
    A("// BUILD SYSTEM what to compile.")
    A("//")
    A("// NOTHING INCLUDES IT TODAY. That is expected, not an oversight: adopting")
    A("// it is app work, and no app has needed it yet. It is generated on every")
    A("// build so it is always correct and current when the first one does.")
    A("//")
    A("// It is NOT the idiom for engine internals. The engine gates itself on the")
    A("// MT_ENABLE_* library flags -- `#ifdef MT_ENABLE_FFMPEG` and friends --")
    A("// because those describe what it actually compiles. This header is the")
    A("// other side of the boundary: what the app ASKED for.")
    A("//")
    A("// TWO THINGS TO USE, and they answer different questions.")
    A("//")
    A("// 1. `MT_REQUIRE_CAP(MT_CAP_HTTP);` -- \"I cannot function without this.\"")
    A("//    A compile-time assertion. A manifest that turns the capability off")
    A("//    then fails to COMPILE, naming the capability, instead of linking and")
    A("//    failing at runtime somewhere unrelated. Put it at file scope in the")
    A("//    TU that depends on the capability.")
    A("//")
    A("// 2. `if (MT_HAS_CAP(MT_CAP_LLM)) { ... }` -- \"adapt to whatever I got.\"")
    A("//    A runtime query, for code that should degrade rather than refuse:")
    A("//    hide a menu item, skip a test, report what this binary supports.")
    A("//    It costs nothing at runtime -- the generated body is a switch over")
    A("//    literals the same run emitted, so the optimiser folds it away.")
    A("//")
    A("// Also here: `MT_GetCapabilityManifest()`, which returns the canonical")
    A("// resolved string this binary was built with. Useful in an about box, a")
    A("// crash report, or a test that wants to record the configuration it ran")
    A("// under.")
    A("//")
    A("// WHAT IS DELIBERATELY ABSENT: MT_COMMERCIAL_BUILD. See the note below.")
    A("//")
    A("// ======================================================================")
    A("//")
    A("// Per-build: this header lives under $MT_OUT/include/, keyed by engine")
    A("// revision, platform, arch, configuration, mode, backend and capability")
    A("// hash. No two builds sharing one engine checkout ever see each other's.")
    A("// It is never committed and never edited; regenerate it instead.")
    A("#pragma once")
    A("")
    A("// ---------------------------------------------------------------------")
    A("// Capabilities. MT_COMMERCIAL_BUILD is DELIBERATELY ABSENT from this file,")
    A("// in every form and at every value. It appears in the canonical resolved")
    A("// string below as 0 or 1 -- so the agreement check can tell \"off\" from")
    A("// \"unset\" -- and, when ON, as a -D on the build-system channel only.")
    A("// This header is on the include path of every engine and app TU, and every")
    A("// guard on that flag in the tree is presence-style: a #define ... 0 here")
    A("// would take all 30 sites down the COMMERCIAL branch, including the")
    A("// licence-audit tests written to catch exactly that.")
    A("// ---------------------------------------------------------------------")
    for key in caps:
        A("#define %-34s %d" % (key, values[key]))
    A("")
    A("// Known-name markers, so MT_REQUIRE_CAP can tell 0 from \"never heard of it\".")
    for key in caps:
        A("#define MT_CAP_DEFINED_%-20s 1" % key)
    A("")
    A("#ifdef __cplusplus")
    A("")
    A("// The enumerators CANNOT be the capability tokens: those are object-like")
    A("// macros defined above, so `enum class MTCapability { MT_CAP_LLM }` expands")
    A("// to `{ 0 }` and does not compile. Short names compile but cannot be reached")
    A("// from a ##-pasting macro, which is what the MT_CAP_ENUM_* aliases below are")
    A("// for. Both constraints, one shape.")
    A("enum class MTCapability")
    A("{")
    for key in caps:
        A("\t%s," % vocab.short(key))
    A("};")
    A("")
    for key in caps:
        A("#define MT_CAP_ENUM_%-22s ::MTCapability::%s" % (key, vocab.short(key)))
    A("")
    A("// `##` suppresses argument pre-expansion, so the call site passes the FULL")
    A("// token -- MT_REQUIRE_CAP(MT_CAP_LLM), never MT_REQUIRE_CAP(LLM). There is no")
    A("// preprocessor operation that strips a MT_CAP_ prefix.")
    A("//")
    A("// The macro expands to two DECLARATIONS and is not do{}while(0)-wrapped, so")
    A("// it belongs at file or class scope, or inside a braced block. Brace it when")
    A("// it follows an `if`: only the first declaration becomes the body, so a")
    A("// trailing `else` has nothing to attach to and you get `expected expression`.")
    A("// Bracing does NOT make the assertion conditional -- nothing can; static_assert")
    A("// is a compile-time construct and fires either way.")
    A("//")
    A("// The call site needs a trailing `;`: the second static_assert has none.")
    A("//")
    A("// A typo does NOT get the friendly message. MT_CAP_DEFINED_MT_CAP_TYPP is not")
    A("// a macro, so it survives as an undeclared identifier and the compiler says")
    A("// `use of undeclared identifier` -- static_assert only emits its message for a")
    A("// valid constant expression that evaluates false. No assert ordering fixes that.")
    A("#define MT_REQUIRE_CAP(cap) \\")
    A("\tstatic_assert(MT_CAP_DEFINED_##cap, #cap \" is not a known capability\"); \\")
    A("\tstatic_assert(cap, #cap \" is required by this host\")")
    A("")
    A("#define MT_HAS_CAP(cap) MT_HasCapability(MT_CAP_ENUM_##cap)")
    A("")
    A("// DEFINED here, not merely declared. `inline` makes it ODR-safe across TUs;")
    A("// a declaration alone links to nothing, and the one path that matters --")
    A("// MT_HAS_CAP -- is exactly the path a compile-only check never exercises.")
    A("inline bool MT_HasCapability(MTCapability cap)")
    A("{")
    A("\tswitch (cap)")
    A("\t{")
    for key in caps:
        A("\t\tcase ::MTCapability::%s: return %s;" % (vocab.short(key), key))
    A("\t}")
    A("\treturn false;")
    A("}")
    A("")
    A("// EXACTLY the canonical resolved form: semicolon-separated, sorted by byte")
    A("// value, no trailing separator. NOT newline-separated -- the in-target")
    A("// backstop compares this against --resolved, and two spellings of \"the same")
    A("// set\" is the mismatch the check exists to prevent.")
    A("inline const char *MT_GetCapabilityManifest()")
    A("{")
    A("\tstatic constexpr char kManifest[] =")
    # MUST track resolve.canonical_form()'s key list exactly -- including both
    # mode keys. These are string-literal CONTENT, not #defines, so they carry
    # none of the `#ifdef X` hazard that keeps MT_COMMERCIAL_BUILD out of this
    # header as a macro; and the backstop compares this text against
    # --resolved, so a key in one and not the other is a guaranteed mismatch.
    for i, key in enumerate(sorted(list(caps) + [COMMERCIAL_KEY, PRIVATE_KEY,
                                                 SYMBOLS_KEY])):
        sep = "" if i == 0 else ";"
        A("\t\t\"%s%s=%d\"" % (sep, key, values[key]))
    A("\t\t;")
    A("\treturn kManifest;")
    A("}")
    A("")
    A("#endif // __cplusplus")
    A("")

    path = os.path.join(include_dir, "MT_Capabilities.h")
    _write(path, "\n".join(L))
    return path


# ---------------------------------------------------------------------------
# The stamp, and the override overlay
# ---------------------------------------------------------------------------

def emit_stamp(out, meta, canonical):
    """resolved.stamp exists because two of `check`'s three callers have no
    manifest. The macOS engine-target backstop and the Windows pre-build target run
    INSIDE the engine project, where the only input is $MT_OUT -- whose key carries
    <app> as a directory name, not a path to c64d/mtengine.caps. So the stamp
    records every resolve input verbatim, and those callers use
    `mtcaps check --stamp <path> --resolved <string>`.

    Without it a backstop can verify only that $MT_OUT is DEFINED, which is a
    presence test and should not be called an agreement check."""
    data = dict(meta)
    data["resolved"] = canonical
    path = os.path.join(out, "resolved.stamp")
    _write(path, json.dumps(data, indent=2, sort_keys=True) + "\n")
    return path


def emit_overrides(out, overrides, meta):
    """A per-build file inside the isolated output root, passed to `check`
    explicitly with --overrides.

    Not beside the app manifest: that is one fixed path per app, so two concurrent
    matrix jobs write and delete each other's overrides and each may resolve with
    the other's keys or with none. A matrix is by definition many builds of one app
    at once, so the fixed-path design broke the exact case it existed to serve.
    Here, two variants have two roots and cannot see each other's file, and an
    ordinary build passes no --overrides and reads none -- staleness is impossible
    rather than cleaned up."""
    lines = ["# %s" % BANNER,
             "# The --set overrides this build resolved with, recorded verbatim so",
             "# `check` re-resolves from the same inputs. Pass it with --overrides;",
             "# it is never discovered by searching.",
             "# app=%s platform=%s resolved-hash=%s" % (meta.get("app"), meta.get("platform"),
                                                        meta.get("caps_hash"))]
    for key in sorted(overrides):
        lines.append("%s=%d" % (key, overrides[key]))
    lines.append("")
    path = os.path.join(out, "overrides.caps")
    _write(path, "\n".join(lines))
    return path


def parse_overrides(path):
    from resolve import parse_manifest
    return {k: v for k, v, _ in parse_manifest(path)}


# ---------------------------------------------------------------------------
# LICENSES.txt
# ---------------------------------------------------------------------------

def emit_licenses(vocab, values, canonical, out, meta):
    """The SBOM, generated from the resolved set AND the core section.

    Derived from the resolved capability set ALONE it would be legally
    incomplete while looking complete: SDL3, zlib, ALSA, GTK3, freetype, libuv,
    ImGui, ImPlot and the committed prebuilts ship outside every capability key.
    That is worse than an obviously partial document, because nobody checks a
    document that appears finished. Both halves are emitted here and Phase 6's
    acceptance asserts both.

    Under the hard-error rule the set asked for and the set built are identical
    by construction, so this is one document describing both.
    """
    L = []
    A = L.append
    A("Third-party licences for %s" % meta.get("app", "(unknown app)"))
    A("=" * 72)
    A("")
    A("Generated by mtcaps from MTEngineSDL/tools/mtcaps/vocabulary.json.")
    A("Do not edit: regenerate instead.")
    A("")
    A("Build: platform=%s arch=%s config=%s mode=%s engine=%s"
      % (meta.get("platform"), meta.get("arch"), meta.get("config"),
         meta.get("mode"), meta.get("rev")))
    if meta.get("engine_options"):
        A("Engine options: %s"
          % ", ".join("%s=%s" % kv for kv in sorted(meta["engine_options"].items())))
        A("  (a CUDA build links NVIDIA components a CPU build does not, which is")
        A("   why these appear here as well as in the output path.)")
    A("")
    A("Resolved capability set:")
    A("  %s" % canonical)
    A("")

    A("-" * 72)
    A("CORE -- always present, belonging to no capability")
    A("-" * 72)
    A("")
    for dep in vocab.core["dependencies"]:
        A("  %s" % dep["name"])
        A("      licence   : %s" % dep["licence"])
        A("      version   : %s" % dep["version"])
        A("      provenance: %s" % dep["provenance"])
        A("")

    on = [k for k in vocab.keys if values[k] == 1]
    off = [k for k in vocab.keys if values[k] == 0]

    A("-" * 72)
    A("ENABLED CAPABILITIES")
    A("-" * 72)
    A("")
    any_dep = False
    for key in on:
        cap = vocab.get(key)
        deps = cap["dependencies"]
        A("  %s -- %s" % (key, cap["description"]))
        if not deps:
            A("      (no third-party dependency)")
        for dep in deps:
            any_dep = True
            A("      %s" % dep["name"])
            A("          licence   : %s" % dep["licence"])
            A("          version   : %s" % dep["version"])
            A("          provenance: %s" % dep["provenance"])
        comm = cap["commercial"]
        if comm["effect"] != "none" and values[COMMERCIAL_KEY] == 1:
            withheld = comm.get("forbidden_decoders_commercial", [])
            A("      commercial mode: %s%s"
              % (comm["effect"],
                 (" -- withheld: " + ", ".join(withheld)) if withheld else ""))
        A("")
    if not any_dep:
        A("  (no third-party dependencies among the enabled capabilities)")
        A("")

    # What the APPLICATION embeds that the vocabulary cannot know about. Read
    # from beside the manifest; absent means the app declares nothing, which
    # is a claim the app makes, not a default this document invents.
    app_deps = load_app_licences(meta["manifest"])
    if app_deps:
        A("-" * 72)
        A("APPLICATION -- declared by the app in %s" % APP_LICENCES_FILE)
        A("-" * 72)
        A("")
        for dep in app_deps:
            A("  %s" % dep["name"])
            A("      licence   : %s" % dep["licence"])
            A("      version   : %s" % dep["version"])
            A("      provenance: %s" % dep["provenance"])
            A("")

    A("-" * 72)
    A("DISABLED CAPABILITIES -- their dependencies are NOT in this build")
    A("-" * 72)
    A("")
    for key in off:
        deps = vocab.get(key)["dependencies"]
        A("  %s%s" % (key, (" (" + ", ".join(d["name"] for d in deps) + ")") if deps else ""))
    A("")

    path = os.path.join(out, "LICENSES.txt")
    _write(path, "\n".join(L) + "\n")
    return path


def emit_llama_version_placeholder(include_dir):
    """A PLACEHOLDER llama_cpp_version.h, so the header always exists.

    CGuiViewLlamaModelLoader.cpp includes it UNCONDITIONALLY, but
    build-llama_cpp.sh -- which used to write it, into a *tracked* file inside the
    engine checkout -- does not run at all when MT_CAP_LLM=0: it emits a stub
    archive and exits. Without this the capability-off build would fail on a
    missing include.

    Never overwrites: when llama IS built, that script writes the real
    `git describe` tag here afterwards and its value must survive re-resolves.
    """
    path = os.path.join(include_dir, "Sci", "Llama", "llama_cpp_version.h")
    if os.path.exists(path):
        return path
    _write(path,
           "// %s\n"
           "// Placeholder. build-llama_cpp.sh overwrites this with the real\n"
           "// `git describe` tag when llama.cpp is actually built.\n"
           "#pragma once\n"
           "#define MT_LLAMA_CPP_VERSION \"not-built\"\n" % BANNER)
    return path


def emit_msbuild_ide_defines(vocab, values, out):
    """Two bare files holding exactly what goes into <PreprocessorDefinitions>.

    They exist because of one MSBuild constraint. `<Import>` is evaluated during
    project EVALUATION, which completes strictly before any target runs -- so a
    Visual Studio build, which passes no /p:MTOutRoot, cannot import the
    generated .props for the build it is in.

    The way around it is not to import at all: a TARGET running BeforeTargets
    ClCompile can modify ClCompile item metadata, because those items are read by
    the task at EXECUTION time. That target needs the define list as a value it
    can read in one step, and MSBuild's property functions are a whitelist of
    static .NET methods -- File::ReadAllText is on it, an XML parse is not.

    So: one flat file per target kind, semicolon-separated, no trailing
    separator, nothing to parse.

    MT_COMMERCIAL_BUILD follows the same rule as everywhere else: present only
    when the mode is on, never as =0.

    platform="windows" throughout: this is the Visual Studio IDE channel and
    nothing else ever reads these two files. See PLATFORM_UNAVAILABLE_FLAGS
    in resolve.py.
    """
    app_defs = list(app_visible_defines(vocab, values, platform="windows"))
    engine_defs = list(app_defs) + list(engine_only_defines(vocab, values, platform="windows"))
    # The engine sees every flag; an app sees only what it guards on. Same split
    # the macOS channel makes, made here by writing two files instead of one.
    for name, defs in (("ide-defines-app.txt", app_defs),
                       ("ide-defines-engine.txt", engine_defs)):
        _write(os.path.join(out, name), ";".join(sorted(set(defs))) + "\n")
    return os.path.join(out, "ide-defines-engine.txt")
