#include "CGuiFontManager.h"
#include "imgui.h"

// MUST precede the textual font_*.cpp includes below. Those definitions are
// `const` at namespace scope and would otherwise have INTERNAL linkage; this
// header's prior `extern` declarations are what make them referenceable from a
// host translation unit ([basic.link]/4). If it moves below them, the symbols
// go back to __ZL... and any host linking against them fails.
// Relative, matching the textual includes below it: this project's own
// HEADER_SEARCH_PATHS do not expose src/Embedded at all -- only hosts do.
#include "../../../Embedded/Fonts/MTEmbeddedFonts.h"

// Embedded font data (compressed C arrays generated by binary_to_compressed_c)
#include "../../../Embedded/Fonts/font_inter_regular.cpp"
#include "../../../Embedded/Fonts/font_inter_bold.cpp"
#include "../../../Embedded/Fonts/font_inter_italic.cpp"
#include "../../../Embedded/Fonts/font_inter_bold_italic.cpp"
#include "../../../Embedded/Fonts/font_jetbrains_mono.cpp"

CGuiFontManager gGuiFontManager;

void CGuiFontManager::LoadMarkdownFonts(float size, float monoSize)
{
    if (markdownFontsLoaded)
        return;

    if (monoSize <= 0.0f)
        monoSize = size;

    ImFontConfig cfg;
    cfg.FontDataOwnedByAtlas = false;

    // Bake Latin + Latin Extended-A/B so non-ASCII scripts (e.g. Polish:
    // ąćęłńśźż) render. Without an explicit range ImGui only bakes 0x20-0xFF.
    static const ImWchar latin_ranges[] = {
        0x0020, 0x00FF,  // Basic Latin + Latin-1 Supplement
        0x0100, 0x017F,  // Latin Extended-A
        0x0180, 0x024F,  // Latin Extended-B
        0x2013, 0x2014,  // en dash, em dash
        0,
    };

    ImFontAtlas* atlas = ImGui::GetIO().Fonts;

    fontRegular    = atlas->AddFontFromMemoryCompressedTTF(font_inter_regular_compressed_data,    (int)font_inter_regular_compressed_size,    size,     &cfg, latin_ranges);
    fontBold       = atlas->AddFontFromMemoryCompressedTTF(font_inter_bold_compressed_data,       (int)font_inter_bold_compressed_size,       size,     &cfg, latin_ranges);
    fontItalic     = atlas->AddFontFromMemoryCompressedTTF(font_inter_italic_compressed_data,     (int)font_inter_italic_compressed_size,     size,     &cfg, latin_ranges);
    fontBoldItalic = atlas->AddFontFromMemoryCompressedTTF(font_inter_bold_italic_compressed_data,(int)font_inter_bold_italic_compressed_size, size,    &cfg, latin_ranges);
    fontMono       = atlas->AddFontFromMemoryCompressedTTF(font_jetbrains_mono_compressed_data,   (int)font_jetbrains_mono_compressed_size,   monoSize, &cfg, latin_ranges);

    markdownFontsLoaded = true;
}
