#include "CGuiFontManager.h"
#include "imgui.h"

// Embedded font data (compressed C arrays generated by binary_to_compressed_c)
#include "../../../../Embedded/Fonts/font_inter_regular.cpp"
#include "../../../../Embedded/Fonts/font_inter_bold.cpp"
#include "../../../../Embedded/Fonts/font_inter_italic.cpp"
#include "../../../../Embedded/Fonts/font_inter_bold_italic.cpp"
#include "../../../../Embedded/Fonts/font_jetbrains_mono.cpp"

CGuiFontManager gGuiFontManager;

void CGuiFontManager::LoadMarkdownFonts(float size, float monoSize)
{
    if (markdownFontsLoaded)
        return;

    if (monoSize <= 0.0f)
        monoSize = size;

    ImFontConfig cfg;
    cfg.FontDataOwnedByAtlas = false;

    ImFontAtlas* atlas = ImGui::GetIO().Fonts;

    fontRegular    = atlas->AddFontFromMemoryCompressedTTF(font_inter_regular_compressed_data,    (int)font_inter_regular_compressed_size,    size,     &cfg);
    fontBold       = atlas->AddFontFromMemoryCompressedTTF(font_inter_bold_compressed_data,       (int)font_inter_bold_compressed_size,       size,     &cfg);
    fontItalic     = atlas->AddFontFromMemoryCompressedTTF(font_inter_italic_compressed_data,     (int)font_inter_italic_compressed_size,     size,     &cfg);
    fontBoldItalic = atlas->AddFontFromMemoryCompressedTTF(font_inter_bold_italic_compressed_data,(int)font_inter_bold_italic_compressed_size, size,    &cfg);
    fontMono       = atlas->AddFontFromMemoryCompressedTTF(font_jetbrains_mono_compressed_data,   (int)font_jetbrains_mono_compressed_size,   monoSize, &cfg);

    markdownFontsLoaded = true;
}
