param(
    [ValidateSet('Debug','Release','RelWithDebInfo','MinSizeRel')]
    [string]$Config = 'Release',
    [ValidateSet('x64','ARM64')]
    [string]$Platform = 'x64',
    [ValidateSet('Clang','MSVC')]
    [string]$Compiler = 'Clang'
)

$ErrorActionPreference = 'Stop'

function Require-Command([string]$name) {
    if (-not (Get-Command $name -ErrorAction SilentlyContinue)) {
        throw "Missing required tool '$name'. Run from 'Developer PowerShell for VS 2022' and ensure CMake is installed." 
    }
}

Require-Command cmake
Require-Command lib

$repoRoot = (Resolve-Path "$PSScriptRoot\..\..").Path
$llamaSrc = Join-Path $repoRoot 'other\lib\llama.cpp'
$buildDir = Join-Path $llamaSrc 'build-windows-cpu'

$outDir = Join-Path $repoRoot "platform\Windows\libs\$Platform\$Config"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

$cmakeToolset = if ($Compiler -eq 'Clang') { @('-T', 'ClangCL') } else { @() }

Write-Host "Configuring llama.cpp (CPU) in $buildDir"
# Auto-detect the default Visual Studio CMake generator for the installed VS
# (handles 'Visual Studio 17 2022', 'Visual Studio 18 2026', ... without hardcoding).
$genMatch = cmake --help | Select-String -Pattern '^\*\s+(Visual Studio \d+ \d+)'
if (-not $genMatch) { throw "Could not detect the default Visual Studio CMake generator from 'cmake --help'." }
$generator = $genMatch.Matches[0].Groups[1].Value
Write-Host "Using CMake generator: $generator"

cmake -S $llamaSrc -B $buildDir -G $generator -A $Platform @cmakeToolset `
    -DBUILD_SHARED_LIBS=OFF `
    -DLLAMA_BUILD_COMMON=OFF `
    -DLLAMA_BUILD_TESTS=OFF `
    -DLLAMA_BUILD_TOOLS=OFF `
    -DLLAMA_BUILD_EXAMPLES=OFF `
    -DLLAMA_BUILD_SERVER=OFF `
    -DLLAMA_TOOLS_INSTALL=OFF `
    -DLLAMA_TESTS_INSTALL=OFF `
    -DGGML_CUDA=OFF `
    -DGGML_VULKAN=OFF

Write-Host "Building llama.cpp libs ($Config)"
cmake --build $buildDir --config $Config --target llama ggml ggml-base ggml-cpu

# VS generator places libs under buildDir\src and buildDir\ggml\src
$libs = @(
    (Join-Path $buildDir "src\$Config\llama.lib"),
    (Join-Path $buildDir "ggml\src\$Config\ggml.lib"),
    (Join-Path $buildDir "ggml\src\$Config\ggml-base.lib"),
    (Join-Path $buildDir "ggml\src\$Config\ggml-cpu.lib")
)

foreach ($p in $libs) {
    if (-not (Test-Path $p)) {
        throw "Expected library not found: $p"
    }
}

$outLib = Join-Path $outDir 'llama_cpp.lib'
Write-Host "Packing into $outLib"
if (Test-Path $outLib) { Remove-Item -Force $outLib }
lib /nologo /OUT:$outLib $libs

Write-Host "Done. Output: $outLib"

# Generate version header from git tag
$versionTag = "unknown"
try {
    $tag = git -C $llamaSrc describe --tags --abbrev=0 2>$null
    if ($tag) { $versionTag = $tag.Trim() }
} catch {}

$versionHeader = Join-Path $repoRoot 'src\Engine\Sci\Llama\llama_cpp_version.h'
@"
// Auto-generated by build-llama_cpp_cpu.ps1 — do not edit
#pragma once
#define MT_LLAMA_CPP_VERSION "$versionTag"
"@ | Set-Content -Path $versionHeader -Encoding UTF8
