param(
    [ValidateSet('Debug','Release','RelWithDebInfo','MinSizeRel')]
    [string]$Config = 'Release',
    [ValidateSet('x64')]
    [string]$Platform = 'x64'
)

$ErrorActionPreference = 'Stop'

function Require-Command([string]$name) {
    if (-not (Get-Command $name -ErrorAction SilentlyContinue)) {
        throw "Missing required tool '$name'. Run from 'Developer PowerShell for VS 2022' and ensure CMake is installed." 
    }
}

Require-Command cmake

if (-not $env:CUDA_PATH) {
    throw "CUDA_PATH is not set. Install NVIDIA CUDA Toolkit and reopen your shell." 
}

$repoRoot = (Resolve-Path "$PSScriptRoot\..\..").Path
$llamaSrc = Join-Path $repoRoot 'other\lib\llama.cpp'
$buildDir = Join-Path $llamaSrc 'build-windows-cuda'

$outDir = Join-Path $repoRoot "platform\Windows\libs\$Platform\$Config"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

Write-Host "Configuring llama.cpp (CUDA) in $buildDir"
cmake -S $llamaSrc -B $buildDir -G "Visual Studio 17 2022" -A $Platform `
    -DBUILD_SHARED_LIBS=OFF `
    -DLLAMA_BUILD_COMMON=OFF `
    -DLLAMA_BUILD_TESTS=OFF `
    -DLLAMA_BUILD_TOOLS=OFF `
    -DLLAMA_BUILD_EXAMPLES=OFF `
    -DLLAMA_BUILD_SERVER=OFF `
    -DLLAMA_TOOLS_INSTALL=OFF `
    -DLLAMA_TESTS_INSTALL=OFF `
    -DGGML_CUDA=ON

Write-Host "Building llama.cpp libs ($Config)"
cmake --build $buildDir --config $Config --target llama ggml ggml-base ggml-cpu ggml-cuda

$copyList = @(
    (Join-Path $buildDir "src\$Config\llama.lib"),
    (Join-Path $buildDir "ggml\src\$Config\ggml.lib"),
    (Join-Path $buildDir "ggml\src\$Config\ggml-base.lib"),
    (Join-Path $buildDir "ggml\src\ggml-cpu\$Config\ggml-cpu.lib"),
    (Join-Path $buildDir "ggml\src\ggml-cuda\$Config\ggml-cuda.lib")
)

foreach ($p in $copyList) {
    if (-not (Test-Path $p)) {
        throw "Expected library not found: $p"
    }
    Copy-Item -Force $p $outDir
}

Write-Host "Done. Copied CUDA libs into: $outDir"

# Generate version header from git tag
$versionTag = "unknown"
try {
    $tag = git -C $llamaSrc describe --tags --abbrev=0 2>$null
    if ($tag) { $versionTag = $tag.Trim() }
} catch {}

$versionHeader = Join-Path $repoRoot 'src\Engine\Sci\Llama\llama_cpp_version.h'
@"
// Auto-generated by build-llama_cpp_cuda.ps1 — do not edit
#pragma once
#define MT_LLAMA_CPP_VERSION "$versionTag"
"@ | Set-Content -Path $versionHeader -Encoding UTF8
